/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dat250assignment1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void ConversionTest(){
        assertEquals(78.7402,App.convertUnit(2, Unit.METERS, Unit.INCHES));
        assertEquals(5280, App.convertUnit(1, Unit.MILES, Unit.FEET));
    }
}